// boolean in js

// A JavaScript Boolean represents one of two values: true or false

// / Boolean Values
// Very often, in programming, you will need a data type that can only have one of two values, like

// YES / NO
// ON / OFF
// TRUE / FALSE

// boolean as function

const res = Boolean(10 > 7);
console.log(res); // true

// also use as 
const res2 = (10 > 8)
console.log(res2); // true

// ? ! Everything With a "Value" is True

// The Boolean value of 0 (zero) is false:
let x = 0;
console.log(Boolean(x)); // false

// The Boolean value of -0 (minus zero) is false:
let y = -0;
console.log(Boolean(y)); // gfgalse

