 // syntax :
 
//  function functionName(parameters){
    
//  }



// ex : 

const person = {
    name : "Dhanush",
    age : 20,
}

        function printName1(){
            console.log(person.name);
        } 
        printName1();
        
      
        
        // parameters : 
        
        function printName(name){
            console.log(name);
        } 
        printName("ram");
        
        
        // Arguments
        
        function ArgumentsPerson(name){
            console.log(name);
        }
        ArgumentsPerson("sam") // arguments