// The JavaScript for loop is used to execute a block of code repeteatedly, until a specified condition evaluates to false. It can be used for iteration if the number of iteration is fixed and known.


// Initialization − The loop initialization expression is where we initialize our counter to a starting value. The initialization statement is executed before the loop begins.

// Condition − The condition expression which will test if a given condition is true or not. If the condition is true, then the code given inside the loop will be executed. Otherwise, the control will come out of the loop.

// Iteration − The iteration expression is where you can increase or decrease your counter.

// for (initialization; condition; iteration) {
    Statement(s) to be executed if condition is true
}