// The JavaScript if...else statement executes a block of code when the specified condition is true. When the condition is false the else block will be executed. The if-else statements can be used to control the flow of execution of a program based on different conditions.


// Types of if statement

// if statement
// if...else statement
// if...else if... statement.


// if statement

// if the condition is true then it execute the condition


// if (expression) {
//     Statement(s) to be executed if expression is true
//  }


// ex :

var age  = 10;

if(age > 5){
    console.log("Your are eligible"); // Your are eligible
}



// if...else statement

// it consists  two  statement  true statement  and false statement  


let age = 15;
if( age > 18 ) {
   result = ;
} else {
   result = "Does not qualify for driving";
}