// The JavaScript switch case is a conditional statement is used to execute different blocks of code depending on the value of an expression. The expression is evaluated, and if it matches the value of one of the case labels, the code block associated with that case is executed. If none of the case labels match the value of the expression, the code block associated with the default label is executed.


// 
// switch (expression) {
//     case condition 1: statement(s)
//     break;
    
//     case condition 2: statement(s)
//     break;
//     ...
    
//     case condition n: statement(s)
//     break;
    
//     default: statement(s)
//  }


