// A while statement in JavaScript creates a loop that executes a block of code repeatedly, as long as the specified condition is true. The condition is evaluated before the execution of the block of code.

// The while loop is an entry-controlled loop.


// while loop
// do while loop

var count = 0;
while (count < 5){    // if the condition is true then the loop is terminated
    console.log(count);
    count++;
}

