// math object in js

console.log(Math.min(45,20)); // to find minimum value
console.log(Math.max(45,20)); // to find maximum value


console.log(Math.abs(-1)); // 1
  // Returns the absolute value of a number (the value without regard to whether it is positive or negative)


 console.log(Math.ceil(45.6));   // 46
 // Returns the smallest integer greater than or equal to the input.
 
 console.log(Math.floor(45.6));  //45
 // returns the greatest integer less than or equal to its numeric argument.
 
 console.log(Math.round(46.7)); // 47
 console.log(Math.round(46.3));  // 46
 // it is used to rounded the value
 
 console.log(Math.pow(3,2)); // 9
 // used to find tje power of the value 
 
 console.log(Math.sqrt(4)); // 2
 // used to find the square root
 
 console.log(Math.trunc(45.3945)); // 45
 // used to trunc the value
 
 console.log(Math.tan(10));
 console.log(Math.cos(10));
 console.log(Math.sin(10));
 
 // trigonometric functions
 
 console.log(Math.sign(-1));
 console.log(Math.sign(1));
 
 
 // logorithm values
 console.log(Math.log(10));
 console.log(Math.log2(10));
 console.log(Math.log1p(10));
 console.log(Math.log10(10));
 
 console.log("--------------------------------------");
 
 // ! mathematical properties
 
  console.log(Math.E);     // returns Euler's number
 console.log(Math.PI);         // returns PI
 console.log(Math.SQRT2);      // returns the square root of 2
 console.log(Math.SQRT1_2);   // returns the square root of 1/2
 console.log(Math.LN2);     // returns the natural logarithm of 2
 console.log(Math.LN10);       // returns the natural logarithm of 10
 console.log(Math.LOG2E);      // returns base 2 logarithm of E
 console.log( Math.LOG10E);    // returns base 10 logarithm of E
 
 