// math object in js

console.log(Math.min(45,20)); // to find minimum value
console.log(Math.max(45,20)); // to find maximum value


console.log(Math.abs(-1)); // 1
  // Returns the absolute value of a number (the value without regard to whether it is positive or negative)


 console.log(Math.ceil(45.6));   // 46
 // Returns the smallest integer greater than or equal to the input.
 
 console.log(Math.floor(45.6));  //45
 // returns the greatest integer less than or equal to its numeric argument.
 
 console.log(Math.round(46.7)); // 47
 console.log(Math.round(46.3));  // 46
 // it is used to rounded the value
 
 console.log(Math.pow(3,2)); // 9
 // used to find tje power of the value 
 
 console.log(Math.sqrt(4)); // 2
 // used to find the square rot