// Escape sequence

// \" values \" is used to add double quotes 


let text = "We are the so-called \"Vikings\" from the north.";
console.log(text);// We are the so-called "Vikings" from the north.



// \'   is used to add single quotes
let text1= 'It\'s alright.';
console.log(text1); // It's alright.

// \\ is used to add backslash in the string
let text2 = "The character \\ is called backslash.";
console.log(text2); // The character \ is called backslash.

// other characters

// \b	Backspace
// \f	Form Feed
// \n	New Line
// \r	Carriage Return
// \t	Horizontal Tabulator
// \v	Vertical Tabulator