// primitive string 

let firstName = 'Dhanush';
let lastName = 'kumar';
let fullName = `DhanushKumar`

// another way to create the string
// object
const name = new String("Ram")
console.log(name);


// property

// to check the length of the values or string
console.log(firstName.length);// 7


// methods

// to check the specif character in a string using charAt() by default value is index of 0 
console.log(firstName.charAt()); // D
console.log(firstName.charAt(1)); // h


console.log(firstName.charCodeAt(0));
console.log(firstName.charCodeAt(A));


