// maps

// A Map holds key-value pairs where the keys can be any datatype.
// A Map remembers the original insertion order of the keys.


// object can override the old value when we gave as new value

// map using constructor method
const mapName = new Map();
// console.log(mapName); 


// Create a Map
const fruits = new Map([
    ["apples", 500],
    ["bananas", 300],
    ["oranges", 200]
  ]);
  
  