// data types in java

// primitive data type
// reference data type

// primitive data type

//   1 => String
//   2 => Integer / Number
//   3 => Boolean
//   4 => undefined  
//   5 => null

// reference data type
//  1 => object
//  2 => Array
//  3 => Function



// primitive data type

let firstName = "Dhanush" // string data type within double quotes
let age = 25   // Integer means number
let result = true // boolean => true or false | 0 or 1
let name;  
console.log(name); // by default you don't have any value is Undefined 


let something = null;  // first you declare null then you can assign value later
something = "some thing"
console.log(something);



// statically typed language

// ex:
String name = "dhhanush"

// dynamic typed language
