// data types in java

// primitive data type
// reference data type

// primitive data type

//   1 => String
//   2 => Integer / Number
//   3 => Boolean
//   4 => undefined  
//   5 => null
//   6 => BigInt
//   7 => Symbol

// reference data type
//  1 => object
//  2 => Array
//  3 => Function



// primitive data type

let firstName = "Dhanush" // string data type within double quotes
let age = 25   // Integer means number
let result = true // boolean => true or false | 0 or 1
let name;  
console.log(name); // by default you don't have any value is Undefined 


let something = null;  // first you declare null then you can assign value later
something = "some thing"
console.log(something);



// statically typed language => c++, c ,java etc...

// ex:
// String name = "dhanush"
// we can declare the data type at the time of declaration

// dynamic typed language  => js, python, php etc...

// ex : 
// name = "dhanush"
// we can't assign data types the compiler automatically assign the datatype 



// string

// we can use string 

// Using the single quote
// Using the double quote
// Using the backticks

let str1 = "Hello World!"; // Using double quotes
let str2 = 'Hello World!'; // Using single quotes
let str3 = `Hello World!`; // Using backticks

console.log(str1);
console.log(str2);
console.log(str3);