// The reserved keywords in JavaScript are predefined keywords used to serve the built-in functionality of the programming language. For example, the var and let keywords are used to define variables, the function keyword is used to define the functions, etc. JavaScript contains more that fifty reserved keywords.


// you can't use the reserved keywords as an identifier


// ex :
// var function = "Hello";   function is keyword used to declare the function


// abstract    	double    	implements	                  return
// arguments    else    	in                  	switch
// await	    enum	    instanceof                  	synchronized
// boolean    	eval	    int                  	this
// break    	export	    interface                  throw
// byte    	    extends	    let                  	throws
// case	        false	    long	                  transient
// catch    	final    	native                  	true
// char      	finally	    new	                  try
// class    	float	    null                  	typeof
// const	    for    	    package                  	var
// continue    	function    private                  	void
// debugger    	goto    	protected                  	volatile
// default    	if	        public                  	yield
// delete    	implements  short                  	while
// do	       import	    static                  	with
// double    	in	    super