// ARITHMETIC OPERATOR

// +   Addition
// - Subtraction
// * multiplication
// / division
// % modulus
// -- increment
// ++ decrement

var x= 20;
var y = 40;

console.log(x + y);
console.log(x - y);
console.log(x * y);
console.log(x / y);
console.log(x % y);

// output :
// 60
// -20
// 800
// 0.5
// 20



// The subtraction operator uses numeric operands but can also be used for non-numeric operands such as strings.

// If both operands are numbers, then resultant is number.

// If any or both operands are strings (containing only numbers), it first converts the strings to number and then performs subtraction operations.

// If string contains non numeric value, it will return NaN.

// If any operand is NaN or Infinity, the result will be NaN or Infinity respectively.





// increment 