// JavaScript Assignment Operators
// The assignment operators in JavaScript are used to assign values to the variables.

// simple assignment operator is equal (=) operator.

// =   (Assignment)	                a = b	 a = b
// +=  (Addition Assignment)	    a += b	 a = a + b
// -=  (Subtraction Assignment)	    a -= b	 a = a – b
// *=  (Multiplication Assignment)	a *= b	 a = a * b
// /=  (Division Assignment)	    a /= b	 a = a / b
// %=  (Remainder Assignment)	    a %= b	 a = a % b
// **= (Exponentiation Assignment)	a **= b	 a = a ** b


// ex :

// ==  simple assignment
const a1 = 25;

// addition assignment
let a = 10;
 a  += 5;  // a = a + 5;
 console.log(a); // 15
 
 // Subtraction Assignment	
 
 let b = 10;
 b  -= 5;  // b = b - 5;
 console.log(b); // 5
 
 
 