// BITWISE AND &
// BITWISE OR
// BIT WISE NOT
// BITWISE NOR
// LEFT SHIFT
//RIGHT SHIFT


// BITWISE AND &

// 0   0    0
// 1   0    0
// 1   1    1
// 0   1    0 


// IF BOTH CONDITION WILL BE TRUE THEN IT  return true otherwise return false



//  bitwise or |

// 0   0    0
// 1   0    1
// 1   1    1
// 0   1    1


// if the any one condition is true then it return true else if the both condition is  false the return false


// bitwise not  ~

// 0    1
// 1    0


it convert the inverse of the intteger