// The comparison operators in JavaScript compare two variables or values and return a boolean value, either true or false based on comparison result.



// Operator	  Description	     Example
// ==	      Equal	              x == y
// !=	      Not Equal	          x != y
// ===	      Strict equality     x === y
// !==	    Strict inequality     x !== y
// >	     Greater than	      x > y
// <	     Less than	          x < y<
// >=	     Greater than or Equal to	 x >= y
// <=	       Less than or Equal to	 x <= y











// Equality (==) Operator

    const a = 10