// The comparison operators in JavaScript compare two variables or values and return a boolean value, either true or false based on comparison result.



// Operator	  Description	     Example
// ==	      Equal	              x == y
// !=	      Not Equal	          x != y
// ===	      Strict equality     x === y
// !==	    Strict inequality     x !== y
// >	     Greater than	      x > y
// <	     Less than	          x < y<
// >=	     Greater than or Equal to	 x >= y
// <=	       Less than or Equal to	 x <= y











// Equality (==) Operator  |   Strict Equality (===) Operator

    const a = 10;
    const b = "10";
    
    console.log(a==b); // true
    console.log(a===b); // false
    
    
    // The "equality" operator checks if the value of two operands are equal or not.
    
    // The "strict equality" operator checks whether the values and data types of the two operands are equal or not.
    
    
    
    // inequality (!=) Operator  |  Strict inequality (!=) Operator  
       
    // The "inequality" operator checks if the values of two operands are not equal.
    
//     10 != 10; // false
// 10 != 20; // true

