// spread operator (…)

// spread operator (…) allows us to spread out elements of an iterable such as an array. The spread operator is represented with three dots (…)

// simple example for spread operator

let x = ["Dhanush", "kumar"];
console.log(x);  // [ 'Dhanush', 'kumar' ] =>  it return as a object
console.log(...x); // Dhanush kumar => it convert the object into the string


// spread operator is also 