// The typeof operator in JavaScript is a unary operator used to get the data type of a particular variable

// syntax :
// typeof operand;

constypeof 10; // returns 'number'
constypeof 'Hello World'; // returns 'string'
constypeof true; // returns 'boolean'
constypeof {name:"Tutorialspoint"}; // returns 'object'
constypeof function foo(){};// returns 'function'
constypeof undefined; // returns 'undefined'
constypeof null; // returns 'object'
constypeof Symbol(); // returns 'symbol'
constypeof 10n; // big int
