// The typeof operator in JavaScript is a unary operator used to get the data type of a particular variable

// syntax :
// typeof operand;

console.log(typeof 10); 
console.log(typeof 'Hello World');
console.log(typeof true); 
console.log(typeof {name:"Tutorialspoint"})
console.log(typeof function foo(){});
console.log(typeof undefined);
console.log(typeof null); // returns 'object'
console.log(typeof Symbol()); // returns 'symbol'
console.log(typeof 10n); // big int
